package defs

const PROTOCOL_DISCONNECT = '0'
const PROTOCOL_REQUEST = '1'
const PROTOCOL_VER = '2'
const PROTOCOL_HOST = '3'
const PROTOCOL_COMPLETION = '4'

const CUSTOMIZE_PROTOCOL = 'c'
const CUSTOMIZE_PROTOCOL_RELOAD = "reload"
